name: sheason_chat
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  get: ^5.0.0-release-candidate-5
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.2
  socket_io_client: ^2.0.3+1
  flutter_webrtc: ^0.9.46
  device_info_plus: ^9.1.1
  cryptography: ^2.7.0
  cryptography_flutter: ^2.3.2
  jwk: ^0.2.3
  barcode_widget: ^2.0.4
  protobuf: ^3.1.0
  fixnum: ^1.1.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  isar_generator: ^3.1.0+1

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
