name: sheason_chat
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.1
  cupertino_icons: ^1.0.2
  socket_io_client: ^2.0.3+1
  flutter_webrtc: ^0.9.46
  device_info_plus: ^9.1.1
  cryptography: ^2.7.0
  cryptography_flutter: ^2.3.2
  jwk: ^0.2.3
  barcode_widget: ^2.0.4
  protobuf: ^3.1.0
  fixnum: ^1.1.0
  path: ^1.8.3
  provider: ^6.1.1
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.0
  mobile_scanner: ^3.5.4
  dio: ^5.3.4
  styled_widget: ^0.4.1
  json_serializable: ^6.7.1
  uuid: ^4.2.1
  json_annotation: ^4.8.1
  random_avatar: ^0.0.8
  scrollable_positioned_list: ^0.3.8
  visibility_detector: ^0.4.0+2
  synchronized: ^3.1.0
  record: ^5.0.1
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  extended_image: ^8.2.0
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  drift_dev: ^2.14.0

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
