name: sheason_chat
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.1
  cupertino_icons: ^1.0.2
  socket_io_client: ^2.0.3+1
  flutter_webrtc: ^0.9.46
  device_info_plus: ^9.1.1
  cryptography: ^2.7.0
  cryptography_flutter: ^2.3.2
  jwk: ^0.2.3
  barcode_widget: ^2.0.4
  protobuf: ^3.1.0
  fixnum: ^1.1.0
  path: ^1.8.3
  provider: ^6.1.1
  drift: ^2.13.0
  sqlite3_flutter_libs: ^0.5.0
  mobile_scanner: ^3.5.4
  dio: ^5.3.4
  styled_widget: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  drift_dev: ^2.13.0

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
