name: Builds
on:
  push:
    branches:
      - master

permissions: read-all

jobs:
  draft-release:
      name: Draft Github release
      runs-on: ubuntu-latest
      outputs:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
      steps:
        - name: Draft release with release notes
          id: create_release
          uses: softprops/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            draft: true
            prerelease: false
            generate_release_notes: true
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        target: ["Android"]
        include:
          - os: ubuntu-latest
            target: Android
            build_target: apk
            build_path: build/app/outputs/flutter-apk
            asset_extension: .apk
            asset_content_type: application/vnd.android.package-archive
    needs: draft-release
    steps:
      - name: Set up JDK
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
        with:
          java-version: 11
          distribution: temurin
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@cc97e1648fff6ca5cc647fa67f47e70f7895510b
        with:
          channel: master
      - run: flutter doctor -v
      - name: Checkout codespace
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - run: |
          cd ./flutter
          flutter pub get
      - run: |
          cd ./flutter
          flutter build -v ${{ matrix.build_target }} --release
      - name: Rename build for Android
        if: matrix.target == 'Android'
        run: mv app-release.apk $GITHUB_WORKSPACE/enc_${{ matrix.target }}.apk
        working-directory: ${{ matrix.build_path }}
      # Upload the build.
      - name: Add packaged build to release draft
        id: upload_release_asset
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5
        with:
          upload_url: ${{ needs.draft-release.outputs.upload_url }}
          asset_path: ./enc_${{ matrix.target }}${{ matrix.asset_extension }}
          asset_name: enc_${{ matrix.target }}${{ matrix.asset_extension }}
          asset_content_type: ${{ matrix.asset_content_type }}
